services:
  - type: web
    name: kms-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install --production=false
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEMO_MODE
        value: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
